# Generated by Django 5.2 on 2025-05-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imagae',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
