# Generated by Django 5.2 on 2025-05-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_menu_imagae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='imagae',
            new_name='image',
        ),
    ]
