# Generated by Django 5.2 on 2025-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_imagae_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='No description available', max_length=500),
        ),
    ]
