# Generated by Django 5.2 on 2025-05-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_menu_type_alter_menu_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeneCatagory',
            new_name='MenuCatagory',
        ),
    ]
